### ISSUE TITLE
Broken Android builds with Flutter 3.24.0

### ISSUE THREAD

**Issue by wrbl606** [segmentio/analytics_flutter#95]
After an upgrade to Flutter 3.24.0 the Android variant of my application is no longer building, with an error:

<details>

```plain
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':flutter_fgbg:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:[PROJECT_DIR]/build/flutter_fgbg/intermediates/merged_res/release/values/values.xml:194: AAPT: error: resource android:attr/lStar not found.
```

</details>

The source of the issue is likely the `flutter_fgbg` dependency -- the maintainers are aware of [the issue](https://github.com/ajinasokan/flutter_fgbg/issues/21), ~~but haven't fixed it yet~~ and it has been [fixed](https://github.com/ajinasokan/flutter_fgbg/issues/21#issuecomment-2296955151) already.

Any plans to mitigate the issue from your side?

**Comment by taham8875** [comment]
Same

**Comment by t-unit** [comment]
The issue on flutter_fgbg seems to have been fixed. See https://github.com/ajinasokan/flutter_fgbg/issues/21#issuecomment-2296955151. So just and update of the dependency is required for this project.

**Comment by QuirijnGB** [comment]
@MichaelGHSeg Its not really fixed until https://github.com/segmentio/analytics_flutter/pull/97 is merged
